###  IMPORTING PANDAS AND READING FILES

In [41]:
import pandas as pd

pl1=pd.read_csv("Data/Annual_P_L_1_final.csv")
pl2=pd.read_csv("Data/Annual_P_L_2_final.csv")

bs=pd.read_csv("Data/Balance_Sheet_final.csv")

cf=pd.read_csv("Data/cash_flow_statments_final.csv")

r1=pd.read_csv("Data/Ratios_1_final.csv")
r2=pd.read_csv("Data/Ratios_2_final.csv")

price=pd.read_csv("Data/Price_final.csv")

### FINDING NO OF ROWS AND COLOUMS IN TABLES

In [42]:
print(pl1.shape)
print(pl2.shape)
print(bs.shape)
print(cf.shape)
print(r1.shape)
print(r2.shape)
print(price.shape)

(4668, 58)
(4668, 30)
(4668, 51)
(4668, 36)
(4668, 50)
(4668, 47)
(4668, 34)

### FINDING WHAT ARE THE COLUMNS PRESENT IN EVERY TABLE

In [43]:
print(pl1.columns)
print(pl2.columns)
print(bs.columns)
print(cf.columns)
print(r1.columns)
print(r2.columns)
print(price.columns)

Index(['Name', 'BSE Code', 'NSE Code', 'Industry', 'Current Price', 'Sales',
       'OPM', 'Profit after tax', 'Return on capital employed', 'EPS',
       'Change in promoter holding', 'Sales last year',
       'Operating profit last year', 'Other income last year',
       'EBIDT last year', 'Depreciation last year', 'EBIT last year',
       'Interest last year', 'Profit before tax last year', 'Tax last year',
       'Profit after tax last year', 'Extraordinary items last year',
       'Net Profit last year', 'Dividend last year', 'Material cost last year',
       'Employee cost last year', 'OPM last year', 'NPM last year',
       'Operating profit', 'Interest', 'Depreciation', 'EPS last year', 'EBIT',
       'Net profit', 'Current Tax', 'Tax', 'Other income',
       'Last annual result date', 'Sales preceding year',
       'Operating profit preceding year', 'Other income preceding year',
       'EBIDT preceding year', 'Depreciation preceding year',
       'EBIT preceding year', 'Interest preceding year',
       'Profit before tax preceding year', 'Tax preceding year',
       'Profit after tax preceding year', 'Extraordinary items preceding year',
       'Net Profit preceding year', 'Dividend preceding year',
       'OPM preceding year', 'NPM preceding year', 'EPS preceding year',
       'Sales preceding 12months', 'Net profit preceding 12months',
       'Market Capitalization', 'join_key'],
      dtype='str')
Index(['Name', 'BSE Code', 'NSE Code', 'Industry', 'Current Price',
       'Sales growth 3Years', 'Sales growth 5Years', 'Profit growth 3Years',
       'Profit growth 5Years', 'Sales growth 10years median',
       'Sales growth 5years median', 'Sales growth 7Years',
       'Sales growth 10Years', 'EBIDT growth 3Years', 'EBIDT growth 5Years',
       'EBIDT growth 7Years', 'EBIDT growth 10Years', 'EPS growth 3Years',
       'EPS growth 5Years', 'EPS growth 7Years', 'EPS growth 10Years',
       'Profit growth 7Years', 'Profit growth 10Years',
       'Change in promoter holding 3Years', 'Average Earnings 5Year',
       'Average Earnings 10Year', 'Average EBIT 5Year', 'Average EBIT 10Year',
       'Market Capitalization', 'join_key'],
      dtype='str')
Index(['Name', 'BSE Code', 'NSE Code', 'Industry', 'Current Price', 'Debt',
       'Equity capital', 'Preference capital', 'Reserves', 'Secured loan',
       'Unsecured loan', 'Balance sheet total', 'Gross block',
       'Revaluation reserve', 'Accumulated depreciation', 'Net block',
       'Capital work in progress', 'Investments', 'Current assets',
       'Current liabilities', 'Book value of unquoted investments',
       'Market value of quoted investments', 'Contingent liabilities',
       'Total Assets', 'Working capital', 'Lease liabilities', 'Inventory',
       'Trade receivables', 'Face value', 'Cash Equivalents',
       'Advance from Customers', 'Trade Payables',
       'Number of equity shares preceding year', 'Debt preceding year',
       'Working capital preceding year', 'Net block preceding year',
       'Gross block preceding year', 'Capital work in progress preceding year',
       'Working capital 3Years back', 'Working capital 5Years back',
       'Working capital 7Years back', 'Working capital 10Years back',
       'Debt 3Years back', 'Debt 5Years back', 'Debt 7Years back',
       'Debt 10Years back', 'Net block 3Years back', 'Net block 5Years back',
       'Net block 7Years back', 'Market Capitalization', 'join_key'],
      dtype='str')
Index(['Name', 'BSE Code', 'NSE Code', 'Industry', 'Current Price',
       'Cash from operations last year', 'Free cash flow last year',
       'Cash from investing last year', 'Cash from financing last year',
       'Net cash flow last year', 'Cash beginning of last year',
       'Cash end of last year', 'Free cash flow preceding year',
       'Cash from operations preceding year',
       'Cash from investing preceding year',
       'Cash from financing preceding year', 'Net cash flow preceding year',
       'Cash beginning of preceding year', 'Cash end of preceding year',
       'Free cash flow 3years', 'Free cash flow 5years',
       'Free cash flow 7years', 'Free cash flow 10years',
       'Operating cash flow 3years', 'Operating cash flow 5years',
       'Operating cash flow 7years', 'Operating cash flow 10years',
       'Investing cash flow 10years', 'Investing cash flow 7years',
       'Investing cash flow 5years', 'Investing cash flow 3years',
       'Cash 3Years back', 'Cash 5Years back', 'Cash 7Years back',
       'Market Capitalization', 'join_key'],
      dtype='str')
Index(['Name', 'BSE Code', 'NSE Code', 'Industry', 'Current Price',
       'Market Capitalization', 'Price to Earning', 'Dividend yield',
       'Price to book value', 'Return on assets', 'Debt to equity',
       'Return on equity', 'Promoter holding', 'Earnings yield',
       'Pledged percentage', 'Industry PE', 'Enterprise Value',
       'Number of equity shares', 'Book value', 'Inventory turnover ratio',
       'Quick ratio', 'Exports percentage', 'Piotroski score', 'G Factor',
       'Asset Turnover Ratio', 'Financial leverage', 'Number of Shareholders',
       'Unpledged promoter holding', 'Return on invested capital',
       'Debtor days', 'Industry PBV', 'Credit rating', 'Working Capital Days',
       'Earning Power', 'Graham Number', 'Cash Conversion Cycle',
       'Days Payable Outstanding', 'Days Receivable Outstanding',
       'Days Inventory Outstanding', 'Public holding', 'FII holding',
       'Change in FII holding', 'Change in DII holding', 'DII holding',
       'Book value preceding year',
       'Return on capital employed preceding year',
       'Return on assets preceding year', 'Return on equity preceding year',
       'Number of Shareholders preceding quarter', 'join_key'],
      dtype='str')
Index(['Name', 'BSE Code', 'NSE Code', 'Industry', 'Current Price',
       'Number of equity shares 10years back',
       'Average return on equity 5Years', 'Average return on equity 3Years',
       'Book value 3years back', 'Book value 5years back',
       'Book value 10years back', 'Inventory turnover ratio 3Years back',
       'Inventory turnover ratio 5Years back',
       'Inventory turnover ratio 7Years back',
       'Inventory turnover ratio 10Years back',
       'Exports percentage 3Years back', 'Exports percentage 5Years back',
       'Average 5years dividend', 'Average return on capital employed 3Years',
       'Average return on capital employed 5Years',
       'Average return on capital employed 7Years',
       'Average return on capital employed 10Years',
       'Average return on equity 10Years', 'Average return on equity 7Years',
       'Return on equity 5years growth', 'OPM 5Year', 'OPM 10Year',
       'Number of Shareholders 1year back', 'Average dividend payout 3years',
       'Average debtor days 3years', 'Debtor days 3years back',
       'Debtor days 5years back', 'Return on assets 5years',
       'Return on assets 3years', 'Historical PE 3Years',
       'Historical PE 10Years', 'Historical PE 7Years', 'Historical PE 5Years',
       'Market Capitalization 3years back',
       'Market Capitalization 5years back',
       'Market Capitalization 7years back',
       'Market Capitalization 10years back',
       'Average Working Capital Days 3years', 'Change in FII holding 3Years',
       'Change in DII holding 3Years', 'Market Capitalization', 'join_key'],
      dtype='str')
Index(['Name', 'BSE Code', 'NSE Code', 'Industry', 'Current Price',
       'Return over 3months', 'Return over 6months', 'Volume 1month average',
       'Volume 1week average', 'Volume', 'High price', 'Low price',
       'High price all time', 'Low price all time', 'Return over 1day',
       'Return over 1week', 'Return over 1month', 'DMA 50', 'DMA 200',
       'DMA 50 previous day', 'DMA 200 previous day', 'RSI', 'MACD',
       'MACD Previous Day', 'MACD Signal', 'MACD Signal Previous Day',
       'Return over 1year', 'Return over 3years', 'Return over 5years',
       'Volume 1year average', 'Return over 7years', 'Return over 10years',
       'Market Capitalization', 'join_key'],
      dtype='str')

### FINDING COMMON COLUMNBS PRESENT IN ALL TABLES

In [44]:
common_columns = set(pl1.columns) 
for df in [pl2, bs, cf, r1, r2, price]:
    common_columns = common_columns.intersection(df.columns)

print("commom coloumns in all tables are:")
print(list(common_columns))

commom coloumns in all tables are:
['Current Price', 'Market Capitalization', 'NSE Code', 'join_key', 'Name', 'BSE Code', 'Industry']

### SORTING COMMON COLUMNS

In [45]:
print(sorted(list(common_columns)))

['BSE Code', 'Current Price', 'Industry', 'Market Capitalization', 'NSE Code', 'Name', 'join_key']

### FINDING FIRST 5 ROWS  OF TABLES

In [46]:
pl1.head(5)

,Name,BSE Code,NSE Code,Industry,Current Price,Sales,OPM,Profit after tax,Return on capital employed,EPS,...,Extraordinary items preceding year,Net Profit preceding year,Dividend preceding year,OPM preceding year,NPM preceding year,EPS preceding year,Sales preceding 12months,Net profit preceding 12months,Market Capitalization,join_key
0,20 Microns,533022.0,20MICRONS,Mining / Minerals / Metals,224.55,777.49,13.59,57.38,21.70,15.89,...,0.00,41.96,2.65,12.23,5.98,11.85,738.43,51.80,792.37,533022.0_20MICRONS
1,21st Cent. Mgmt.,526921.0,21STCENMGM,Finance & Investments,70.44,34.92,94.27,32.23,73.00,30.70,...,0.00,-15.58,0.00,-115.06,NaN,-14.84,11.94,9.93,73.96,526921.0_21STCENMGM
2,360 ONE,542772.0,360ONE,Finance & Investments,1009.40,2920.91,58.37,804.18,14.47,22.41,...,0.01,657.89,2457.09,62.77,31.99,18.48,2245.61,717.01,36627.84,542772.0_360ONE
3,3B Blackbio,532067.0,__NA__,Healthcare,1182.00,74.12,44.50,32.10,20.95,38.13,...,0.00,25.94,1.87,47.12,41.95,34.55,69.24,28.49,1014.49,532067.0___NA__
4,3C IT Solutions,544190.0,__NA__,Computers - Software - Medium / Small,44.01,61.93,5.17,1.14,25.63,31.67,...,0.00,1.11,0.00,4.21,1.66,1110.00,NaN,NaN,26.50,544190.0___NA__

In [47]:
pl2.head(5)

,Name,BSE Code,NSE Code,Industry,Current Price,Sales growth 3Years,Sales growth 5Years,Profit growth 3Years,Profit growth 5Years,Sales growth 10years median,...,EPS growth 10Years,Profit growth 7Years,Profit growth 10Years,Change in promoter holding 3Years,Average Earnings 5Year,Average Earnings 10Year,Average EBIT 5Year,Average EBIT 10Year,Market Capitalization,join_key
0,20 Microns,533022.0,20MICRONS,Mining / Minerals / Metals,224.65,17.15,10.14,35.20,17.97,9.98,...,48.07,20.05,48.68,0.12,36.19,24.91,68.28,56.31,792.72,533022.0_20MICRONS
1,21st Cent. Mgmt.,526921.0,21STCENMGM,Finance & Investments,70.44,NaN,32.41,121.08,42.37,-33.33,...,62.19,79.29,62.19,3.62,-2.82,2.22,-2.63,3.60,73.96,526921.0_21STCENMGM
2,360 ONE,542772.0,360ONE,Finance & Investments,1007.00,20.86,13.10,29.42,16.51,-0.73,...,NaN,NaN,NaN,-5.16,522.53,NaN,1142.50,NaN,36540.75,542772.0_360ONE
3,3B Blackbio,532067.0,__NA__,Healthcare,1186.85,-31.11,26.06,-34.43,43.69,-6.75,...,51.35,61.30,55.84,2.94,42.36,22.22,57.19,30.33,1018.66,532067.0___NA__
4,3C IT Solutions,544190.0,__NA__,Computers - Software - Medium / Small,44.01,NaN,NaN,NaN,NaN,-7.32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.50,544190.0___NA__

In [48]:
bs.head(5)

,Name,BSE Code,NSE Code,Industry,Current Price,Debt,Equity capital,Preference capital,Reserves,Secured loan,...,Working capital 10Years back,Debt 3Years back,Debt 5Years back,Debt 7Years back,Debt 10Years back,Net block 3Years back,Net block 5Years back,Net block 7Years back,Market Capitalization,join_key
0,20 Microns,533022.0,20MICRONS,Mining / Minerals / Metals,225.45,121.37,17.64,0.0,335.31,82.32,...,50.93,104.16,124.45,152.01,176.64,202.58,194.99,177.00,795.54,533022.0_20MICRONS
1,21st Cent. Mgmt.,526921.0,21STCENMGM,Finance & Investments,70.44,4.17,10.50,0.0,42.88,0.00,...,5.49,0.00,0.00,0.00,0.06,0.16,0.31,0.89,73.96,526921.0_21STCENMGM
2,360 ONE,542772.0,360ONE,Finance & Investments,999.10,9471.93,35.89,0.0,3413.84,7636.08,...,NaN,5076.69,6103.08,NaN,NaN,837.19,336.60,NaN,36254.08,542772.0_360ONE
3,3B Blackbio,532067.0,__NA__,Healthcare,1194.20,0.85,8.57,0.0,214.48,1.12,...,13.43,2.01,6.19,8.69,6.89,5.00,3.97,3.28,1024.98,532067.0___NA__
4,3C IT Solutions,544190.0,__NA__,Computers - Software - Medium / Small,44.10,13.40,0.36,0.0,3.74,9.54,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.55,544190.0___NA__

In [49]:
cf.head(5)

,Name,BSE Code,NSE Code,Industry,Current Price,Cash from operations last year,Free cash flow last year,Cash from investing last year,Cash from financing last year,Net cash flow last year,...,Operating cash flow 10years,Investing cash flow 10years,Investing cash flow 7years,Investing cash flow 5years,Investing cash flow 3years,Cash 3Years back,Cash 5Years back,Cash 7Years back,Market Capitalization,join_key
0,20 Microns,533022.0,20MICRONS,Mining / Minerals / Metals,225.65,54.44,34.82,-23.11,-2.86,28.46,...,463.86,-143.91,-126.05,-89.01,-63.95,9.94,10.74,10.27,796.25,533022.0_20MICRONS
1,21st Cent. Mgmt.,526921.0,21STCENMGM,Finance & Investments,70.44,-1.76,-1.80,14.08,-8.83,3.49,...,4.52,-21.33,1.87,-7.00,-7.01,1.17,15.78,5.82,73.96,526921.0_21STCENMGM
2,360 ONE,542772.0,360ONE,Finance & Investments,999.55,-470.11,-571.18,-1574.38,1977.74,-66.75,...,NaN,NaN,-2207.85,-1146.91,-1914.61,838.19,277.42,NaN,36270.41,542772.0_360ONE
3,3B Blackbio,532067.0,__NA__,Healthcare,1190.00,26.95,26.44,-20.32,-3.63,3.01,...,199.10,-109.40,-108.95,-107.24,-36.34,35.08,3.37,0.43,1021.38,532067.0___NA__
4,3C IT Solutions,544190.0,__NA__,Computers - Software - Medium / Small,44.10,-2.20,-2.72,0.47,1.03,-0.70,...,NaN,NaN,NaN,NaN,0.42,NaN,NaN,NaN,26.55,544190.0___NA__

In [50]:
r1.head(5)

,Name,BSE Code,NSE Code,Industry,Current Price,Market Capitalization,Price to Earning,Dividend yield,Price to book value,Return on assets,...,FII holding,Change in FII holding,Change in DII holding,DII holding,Book value preceding year,Return on capital employed preceding year,Return on assets preceding year,Return on equity preceding year,Number of Shareholders preceding quarter,join_key
0,20 Microns,533022.0,20MICRONS,Mining / Minerals / Metals,225.65,796.25,13.84,0.57,2.30,10.35,...,0.73,0.01,0.00,0.00,83.20,19.27,8.10,15.34,20546.0,533022.0_20MICRONS
1,21st Cent. Mgmt.,526921.0,21STCENMGM,Finance & Investments,70.44,73.96,2.30,3.54,1.39,64.72,...,0.00,0.00,0.00,0.00,18.87,-43.10,-38.53,-62.72,6333.0,526921.0_21STCENMGM
2,360 ONE,542772.0,360ONE,Finance & Investments,997.60,36199.65,45.05,1.63,10.36,6.11,...,63.22,0.74,-0.53,8.34,87.67,13.33,6.00,21.41,42622.0,542772.0_360ONE
3,3B Blackbio,532067.0,__NA__,Healthcare,1184.50,1016.66,31.66,0.21,4.54,13.89,...,2.97,-0.41,0.71,1.89,228.05,19.06,12.77,16.00,10088.0,532067.0___NA__
4,3C IT Solutions,544190.0,__NA__,Computers - Software - Medium / Small,44.10,26.55,23.30,0.00,NaN,3.59,...,0.00,NaN,NaN,0.00,NaN,29.33,4.19,53.37,NaN,544190.0___NA__

In [51]:
r2.head(5)

,Name,BSE Code,NSE Code,Industry,Current Price,Number of equity shares 10years back,Average return on equity 5Years,Average return on equity 3Years,Book value 3years back,Book value 5years back,...,Historical PE 5Years,Market Capitalization 3years back,Market Capitalization 5years back,Market Capitalization 7years back,Market Capitalization 10years back,Average Working Capital Days 3years,Change in FII holding 3Years,Change in DII holding 3Years,Market Capitalization,join_key
0,20 Microns,533022.0,20MICRONS,Mining / Minerals / Metals,225.20,3.38,14.98,16.11,60.78,53.22,...,8.23,124.03,134.79,123.50,105.34,84.01,0.70,0.00,794.66,533022.0_20MICRONS
1,21st Cent. Mgmt.,526921.0,21STCENMGM,Finance & Investments,70.44,1.05,-6.55,1.40,48.70,52.02,...,4.69,14.65,20.21,19.16,4.25,51.05,-0.35,-0.15,73.96,526921.0_21STCENMGM
2,360 ONE,542772.0,360ONE,Finance & Investments,994.55,NaN,17.25,21.97,80.43,85.77,...,29.05,10894.33,NaN,NaN,NaN,-109.10,38.31,6.97,36088.98,542772.0_360ONE
3,3B Blackbio,532067.0,__NA__,Healthcare,1184.50,0.64,34.65,17.98,175.88,42.77,...,10.69,213.76,48.38,22.11,4.79,210.92,1.50,1.80,1016.66,532067.0___NA__
4,3C IT Solutions,544190.0,__NA__,Computers - Software - Medium / Small,44.10,NaN,NaN,NaN,NaN,NaN,...,1.51,NaN,NaN,NaN,NaN,64.30,NaN,NaN,26.55,544190.0___NA__

In [52]:
price.head(5)

,Name,BSE Code,NSE Code,Industry,Current Price,Return over 3months,Return over 6months,Volume 1month average,Volume 1week average,Volume,...,MACD Signal,MACD Signal Previous Day,Return over 1year,Return over 3years,Return over 5years,Volume 1year average,Return over 7years,Return over 10years,Market Capitalization,join_key
0,20 Microns,533022.0,20MICRONS,Mining / Minerals / Metals,225.20,44.62,23.16,729846,816052,312746,...,9.09,8.16,134.11,55.29,41.55,203559,28.58,20.15,794.66,533022.0_20MICRONS
1,21st Cent. Mgmt.,526921.0,21STCENMGM,Finance & Investments,70.44,54.12,114.43,34120,27069,11745,...,3.19,2.91,185.75,41.50,30.34,13416,15.32,24.91,73.96,526921.0_21STCENMGM
2,360 ONE,542772.0,360ONE,Finance & Investments,995.85,40.86,49.58,1193124,2871837,5329590,...,20.92,16.98,115.42,50.50,NaN,705325,NaN,NaN,36136.15,542772.0_360ONE
3,3B Blackbio,532067.0,__NA__,Healthcare,1184.50,48.07,25.94,21265,5355,7221,...,81.34,82.28,165.64,22.40,64.50,13985,54.44,64.15,1016.66,532067.0___NA__
4,3C IT Solutions,544190.0,__NA__,Computers - Software - Medium / Small,45.00,NaN,NaN,159500,81000,74000,...,0.72,0.82,NaN,NaN,NaN,159500,NaN,NaN,27.09,544190.0___NA__

### KNOWING INFORMATION OF TABLES

In [53]:
pl1.info()
pl2.info()
bs.info()
cf.info()
r1.info()
r2.info()
price.info()

<class 'pandas.DataFrame'>
RangeIndex: 4668 entries, 0 to 4667
Data columns (total 58 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Name                                4668 non-null   str
 1   BSE Code                            4668 non-null   float64
 2   NSE Code                            4668 non-null   str
 3   Industry                            4668 non-null   str
 4   Current Price                       4667 non-null   float64
 5   Sales                               4664 non-null   float64
 6   OPM                                 4367 non-null   float64
 7   Profit after tax                    4664 non-null   float64
 8   Return on capital employed          4451 non-null   float64
 9   EPS                                 4640 non-null   float64
 10  Change in promoter holding          4553 non-null   float64
 11  Sales last year                     4665 non-null   float64
 12  Operating profit last year          4665 non-null   float64
 13  Other income last year              4665 non-null   float64
 14  EBIDT last year                     4665 non-null   float64
 15  Depreciation last year              4665 non-null   float64
 16  EBIT last year                      4665 non-null   float64
 17  Interest last year                  4665 non-null   float64
 18  Profit before tax last year         4665 non-null   float64
 19  Tax last year                       4665 non-null   float64
 20  Profit after tax last year          4665 non-null   float64
 21  Extraordinary items last year       4665 non-null   float64
 22  Net Profit last year                4665 non-null   float64
 23  Dividend last year                  4665 non-null   float64
 24  Material cost last year             4367 non-null   float64
 25  Employee cost last year             4665 non-null   float64
 26  OPM last year                       4367 non-null   float64
 27  NPM last year                       4460 non-null   float64
 28  Operating profit                    4664 non-null   float64
 29  Interest                            4664 non-null   float64
 30  Depreciation                        4664 non-null   float64
 31  EPS last year                       4641 non-null   float64
 32  EBIT                                4664 non-null   float64
 33  Net profit                          4664 non-null   float64
 34  Current Tax                         4664 non-null   float64
 35  Tax                                 4664 non-null   float64
 36  Other income                        4664 non-null   float64
 37  Last annual result date             4665 non-null   float64
 38  Sales preceding year                4625 non-null   float64
 39  Operating profit preceding year     4625 non-null   float64
 40  Other income preceding year         4625 non-null   float64
 41  EBIDT preceding year                4625 non-null   float64
 42  Depreciation preceding year         4625 non-null   float64
 43  EBIT preceding year                 4625 non-null   float64
 44  Interest preceding year             4625 non-null   float64
 45  Profit before tax preceding year    4625 non-null   float64
 46  Tax preceding year                  4625 non-null   float64
 47  Profit after tax preceding year     4625 non-null   float64
 48  Extraordinary items preceding year  4625 non-null   float64
 49  Net Profit preceding year           4625 non-null   float64
 50  Dividend preceding year             4625 non-null   float64
 51  OPM preceding year                  4359 non-null   float64
 52  NPM preceding year                  4428 non-null   float64
 53  EPS preceding year                  4541 non-null   float64
 54  Sales preceding 12months            3969 non-null   float64
 55  Net profit preceding 12months       3969 non-null   float64
 56  Market Capitalization               4668 non-null   float64
 57  join_key                            4668 non-null   str
dtypes: float64(54), str(4)
memory usage: 2.1 MB
<class 'pandas.DataFrame'>
RangeIndex: 4668 entries, 0 to 4667
Data columns (total 30 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Name                               4668 non-null   str
 1   BSE Code                           4668 non-null   float64
 2   NSE Code                           4668 non-null   str
 3   Industry                           4668 non-null   str
 4   Current Price                      4667 non-null   float64
 5   Sales growth 3Years                4055 non-null   float64
 6   Sales growth 5Years                3691 non-null   float64
 7   Profit growth 3Years               3891 non-null   float64
 8   Profit growth 5Years               3453 non-null   float64
 9   Sales growth 10years median        4577 non-null   float64
 10  Sales growth 5years median         4534 non-null   float64
 11  Sales growth 7Years                3330 non-null   float64
 12  Sales growth 10Years               2936 non-null   float64
 13  EBIDT growth 3Years                4042 non-null   float64
 14  EBIDT growth 5Years                3638 non-null   float64
 15  EBIDT growth 7Years                3237 non-null   float64
 16  EBIDT growth 10Years               2795 non-null   float64
 17  EPS growth 3Years                  3839 non-null   float64
 18  EPS growth 5Years                  3427 non-null   float64
 19  EPS growth 7Years                  3051 non-null   float64
 20  EPS growth 10Years                 2618 non-null   float64
 21  Profit growth 7Years               3051 non-null   float64
 22  Profit growth 10Years              2636 non-null   float64
 23  Change in promoter holding 3Years  3971 non-null   float64
 24  Average Earnings 5Year             4283 non-null   float64
 25  Average Earnings 10Year            3434 non-null   float64
 26  Average EBIT 5Year                 4283 non-null   float64
 27  Average EBIT 10Year                3434 non-null   float64
 28  Market Capitalization              4668 non-null   float64
 29  join_key                           4668 non-null   str
dtypes: float64(26), str(4)
memory usage: 1.1 MB
<class 'pandas.DataFrame'>
RangeIndex: 4668 entries, 0 to 4667
Data columns (total 51 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Name                                     4668 non-null   str
 1   BSE Code                                 4668 non-null   float64
 2   NSE Code                                 4668 non-null   str
 3   Industry                                 4668 non-null   str
 4   Current Price                            4667 non-null   float64
 5   Debt                                     4652 non-null   float64
 6   Equity capital                           4632 non-null   float64
 7   Preference capital                       4559 non-null   float64
 8   Reserves                                 4652 non-null   float64
 9   Secured loan                             4559 non-null   float64
 10  Unsecured loan                           4559 non-null   float64
 11  Balance sheet total                      4652 non-null   float64
 12  Gross block                              4559 non-null   float64
 13  Revaluation reserve                      4559 non-null   float64
 14  Accumulated depreciation                 4559 non-null   float64
 15  Net block                                4652 non-null   float64
 16  Capital work in progress                 4652 non-null   float64
 17  Investments                              4652 non-null   float64
 18  Current assets                           4652 non-null   float64
 19  Current liabilities                      4652 non-null   float64
 20  Book value of unquoted investments       4559 non-null   float64
 21  Market value of quoted investments       4559 non-null   float64
 22  Contingent liabilities                   4559 non-null   float64
 23  Total Assets                             4652 non-null   float64
 24  Working capital                          4652 non-null   float64
 25  Lease liabilities                        4652 non-null   float64
 26  Inventory                                4652 non-null   float64
 27  Trade receivables                        4652 non-null   float64
 28  Face value                               4642 non-null   float64
 29  Cash Equivalents                         4652 non-null   float64
 30  Advance from Customers                   4559 non-null   float64
 31  Trade Payables                           4652 non-null   float64
 32  Number of equity shares preceding year   4541 non-null   float64
 33  Debt preceding year                      4614 non-null   float64
 34  Working capital preceding year           4614 non-null   float64
 35  Net block preceding year                 4614 non-null   float64
 36  Gross block preceding year               4585 non-null   float64
 37  Capital work in progress preceding year  4614 non-null   float64
 38  Working capital 3Years back              4466 non-null   float64
 39  Working capital 5Years back              4087 non-null   float64
 40  Working capital 7Years back              3723 non-null   float64
 41  Working capital 10Years back             3332 non-null   float64
 42  Debt 3Years back                         4466 non-null   float64
 43  Debt 5Years back                         4087 non-null   float64
 44  Debt 7Years back                         3723 non-null   float64
 45  Debt 10Years back                        3332 non-null   float64
 46  Net block 3Years back                    4466 non-null   float64
 47  Net block 5Years back                    4087 non-null   float64
 48  Net block 7Years back                    3723 non-null   float64
 49  Market Capitalization                    4668 non-null   float64
 50  join_key                                 4668 non-null   str
dtypes: float64(47), str(4)
memory usage: 1.8 MB
<class 'pandas.DataFrame'>
RangeIndex: 4668 entries, 0 to 4667
Data columns (total 36 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Name                                 4668 non-null   str
 1   BSE Code                             4668 non-null   float64
 2   NSE Code                             4668 non-null   str
 3   Industry                             4668 non-null   str
 4   Current Price                        4667 non-null   float64
 5   Cash from operations last year       4653 non-null   float64
 6   Free cash flow last year             4653 non-null   float64
 7   Cash from investing last year        4653 non-null   float64
 8   Cash from financing last year        4653 non-null   float64
 9   Net cash flow last year              4653 non-null   float64
 10  Cash beginning of last year          4653 non-null   float64
 11  Cash end of last year                4632 non-null   float64
 12  Free cash flow preceding year        4621 non-null   float64
 13  Cash from operations preceding year  4621 non-null   float64
 14  Cash from investing preceding year   4621 non-null   float64
 15  Cash from financing preceding year   4621 non-null   float64
 16  Net cash flow preceding year         4621 non-null   float64
 17  Cash beginning of preceding year     4621 non-null   float64
 18  Cash end of preceding year           4614 non-null   float64
 19  Free cash flow 3years                4535 non-null   float64
 20  Free cash flow 5years                4252 non-null   float64
 21  Free cash flow 7years                3807 non-null   float64
 22  Free cash flow 10years               3335 non-null   float64
 23  Operating cash flow 3years           4535 non-null   float64
 24  Operating cash flow 5years           4252 non-null   float64
 25  Operating cash flow 7years           3807 non-null   float64
 26  Operating cash flow 10years          3335 non-null   float64
 27  Investing cash flow 10years          3335 non-null   float64
 28  Investing cash flow 7years           3807 non-null   float64
 29  Investing cash flow 5years           4252 non-null   float64
 30  Investing cash flow 3years           4535 non-null   float64
 31  Cash 3Years back                     4466 non-null   float64
 32  Cash 5Years back                     4087 non-null   float64
 33  Cash 7Years back                     3723 non-null   float64
 34  Market Capitalization                4668 non-null   float64
 35  join_key                             4668 non-null   str
dtypes: float64(32), str(4)
memory usage: 1.3 MB
<class 'pandas.DataFrame'>
RangeIndex: 4668 entries, 0 to 4667
Data columns (total 50 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Name                                       4668 non-null   str
 1   BSE Code                                   4668 non-null   float64
 2   NSE Code                                   4668 non-null   str
 3   Industry                                   4668 non-null   str
 4   Current Price                              4667 non-null   float64
 5   Market Capitalization                      4668 non-null   float64
 6   Price to Earning                           3627 non-null   float64
 7   Dividend yield                             4642 non-null   float64
 8   Price to book value                        4174 non-null   float64
 9   Return on assets                           4606 non-null   float64
 10  Debt to equity                             4310 non-null   float64
 11  Return on equity                           4233 non-null   float64
 12  Promoter holding                           4653 non-null   float64
 13  Earnings yield                             4651 non-null   float64
 14  Pledged percentage                         4653 non-null   float64
 15  Industry PE                                4646 non-null   float64
 16  Enterprise Value                           4652 non-null   float64
 17  Number of equity shares                    4648 non-null   float64
 18  Book value                                 4540 non-null   float64
 19  Inventory turnover ratio                   3501 non-null   float64
 20  Quick ratio                                4647 non-null   float64
 21  Exports percentage                         4289 non-null   float64
 22  Piotroski score                            4668 non-null   float64
 23  G Factor                                   4668 non-null   float64
 24  Asset Turnover Ratio                       4606 non-null   float64
 25  Financial leverage                         4606 non-null   float64
 26  Number of Shareholders                     4591 non-null   float64
 27  Unpledged promoter holding                 4653 non-null   float64
 28  Return on invested capital                 4546 non-null   float64
 29  Debtor days                                4335 non-null   float64
 30  Industry PBV                               4659 non-null   float64
 31  Credit rating                              0 non-null      float64
 32  Working Capital Days                       4335 non-null   float64
 33  Earning Power                              4649 non-null   float64
 34  Graham Number                              3444 non-null   float64
 35  Cash Conversion Cycle                      4335 non-null   float64
 36  Days Payable Outstanding                   3001 non-null   float64
 37  Days Receivable Outstanding                4335 non-null   float64
 38  Days Inventory Outstanding                 3245 non-null   float64
 39  Public holding                             4591 non-null   float64
 40  FII holding                                4591 non-null   float64
 41  Change in FII holding                      4443 non-null   float64
 42  Change in DII holding                      4443 non-null   float64
 43  DII holding                                4591 non-null   float64
 44  Book value preceding year                  4226 non-null   float64
 45  Return on capital employed preceding year  4435 non-null   float64
 46  Return on assets preceding year            4540 non-null   float64
 47  Return on equity preceding year            4150 non-null   float64
 48  Number of Shareholders preceding quarter   4443 non-null   float64
 49  join_key                                   4668 non-null   str
dtypes: float64(46), str(4)
memory usage: 1.8 MB
<class 'pandas.DataFrame'>
RangeIndex: 4668 entries, 0 to 4667
Data columns (total 47 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Name                                        4668 non-null   str
 1   BSE Code                                    4668 non-null   float64
 2   NSE Code                                    4668 non-null   str
 3   Industry                                    4668 non-null   str
 4   Current Price                               4667 non-null   float64
 5   Number of equity shares 10years back        3392 non-null   float64
 6   Average return on equity 5Years             3567 non-null   float64
 7   Average return on equity 3Years             3979 non-null   float64
 8   Book value 3years back                      3844 non-null   float64
 9   Book value 5years back                      3726 non-null   float64
 10  Book value 10years back                     2756 non-null   float64
 11  Inventory turnover ratio 3Years back        3300 non-null   float64
 12  Inventory turnover ratio 5Years back        3172 non-null   float64
 13  Inventory turnover ratio 7Years back        2946 non-null   float64
 14  Inventory turnover ratio 10Years back       2636 non-null   float64
 15  Exports percentage 3Years back              4261 non-null   float64
 16  Exports percentage 5Years back              4111 non-null   float64
 17  Average 5years dividend                     4283 non-null   float64
 18  Average return on capital employed 3Years   4668 non-null   float64
 19  Average return on capital employed 5Years   4668 non-null   float64
 20  Average return on capital employed 7Years   4668 non-null   float64
 21  Average return on capital employed 10Years  4668 non-null   float64
 22  Average return on equity 10Years            2752 non-null   float64
 23  Average return on equity 7Years             3176 non-null   float64
 24  Return on equity 5years growth              2920 non-null   float64
 25  OPM 5Year                                   3945 non-null   float64
 26  OPM 10Year                                  3047 non-null   float64
 27  Number of Shareholders 1year back           4222 non-null   float64
 28  Average dividend payout 3years              4476 non-null   float64
 29  Average debtor days 3years                  4668 non-null   float64
 30  Debtor days 3years back                     4212 non-null   float64
 31  Debtor days 5years back                     3887 non-null   float64
 32  Return on assets 5years                     4065 non-null   float64
 33  Return on assets 3years                     4449 non-null   float64
 34  Historical PE 3Years                        4196 non-null   float64
 35  Historical PE 10Years                       4486 non-null   float64
 36  Historical PE 7Years                        4413 non-null   float64
 37  Historical PE 5Years                        4329 non-null   float64
 38  Market Capitalization 3years back           3929 non-null   float64
 39  Market Capitalization 5years back           3739 non-null   float64
 40  Market Capitalization 7years back           3331 non-null   float64
 41  Market Capitalization 10years back          2813 non-null   float64
 42  Average Working Capital Days 3years         4668 non-null   float64
 43  Change in FII holding 3Years                3962 non-null   float64

### CHECKING DUPLICATES

In [54]:
print(pl1.duplicated() .any())
print(pl2.duplicated() .any())
print(bs.duplicated() .any())
print(cf.duplicated() .any())
print(r1.duplicated() .any())
print(r2.duplicated() .any())
print(price.duplicated() .any())

False
False
False
False
False
False
False

### CHECKING NUMBER OF NULL VALUES

In [55]:
print(pl1.isnull().sum())
print(pl2.isnull().sum())
print(bs.isnull().sum())
print(cf.isnull().sum())
print(r1.isnull().sum())
print(r2.isnull().sum())
print(price.isnull())

Name                                    0
BSE Code                                0
NSE Code                                0
Industry                                0
Current Price                           1
Sales                                   4
OPM                                   301
Profit after tax                        4
Return on capital employed            217
EPS                                    28
Change in promoter holding            115
Sales last year                         3
Operating profit last year              3
Other income last year                  3
EBIDT last year                         3
Depreciation last year                  3
EBIT last year                          3
Interest last year                      3
Profit before tax last year             3
Tax last year                           3
Profit after tax last year              3
Extraordinary items last year           3
Net Profit last year                    3
Dividend last year                      3
Material cost last year               301
Employee cost last year                 3
OPM last year                         301
NPM last year                         208
Operating profit                        4
Interest                                4
Depreciation                            4
EPS last year                          27
EBIT                                    4
Net profit                              4
Current Tax                             4
Tax                                     4
Other income                            4
Last annual result date                 3
Sales preceding year                   43
Operating profit preceding year        43
Other income preceding year            43
EBIDT preceding year                   43
Depreciation preceding year            43
EBIT preceding year                    43
Interest preceding year                43
Profit before tax preceding year       43
Tax preceding year                     43
Profit after tax preceding year        43
Extraordinary items preceding year     43
Net Profit preceding year              43
Dividend preceding year                43
OPM preceding year                    309
NPM preceding year                    240
EPS preceding year                    127
Sales preceding 12months              699
Net profit preceding 12months         699
Market Capitalization                   0
join_key                                0
dtype: int64
Name                                    0
BSE Code                                0
NSE Code                                0
Industry                                0
Current Price                           1
Sales growth 3Years                   613
Sales growth 5Years                   977
Profit growth 3Years                  777
Profit growth 5Years                 1215
Sales growth 10years median            91
Sales growth 5years median            134
Sales growth 7Years                  1338
Sales growth 10Years                 1732
EBIDT growth 3Years                   626
EBIDT growth 5Years                  1030
EBIDT growth 7Years                  1431
EBIDT growth 10Years                 1873
EPS growth 3Years                     829
EPS growth 5Years                    1241
EPS growth 7Years                    1617
EPS growth 10Years                   2050
Profit growth 7Years                 1617
Profit growth 10Years                2032
Change in promoter holding 3Years     697
Average Earnings 5Year                385
Average Earnings 10Year              1234
Average EBIT 5Year                    385
Average EBIT 10Year                  1234
Market Capitalization                   0
join_key                                0
dtype: int64
Name                                          0
BSE Code                                      0
NSE Code                                      0
Industry                                      0
Current Price                                 1
Debt                                         16
Equity capital                               36
Preference capital                          109
Reserves                                     16
Secured loan                                109
Unsecured loan                              109
Balance sheet total                          16
Gross block                                 109
Revaluation reserve                         109
Accumulated depreciation                    109
Net block                                    16
Capital work in progress                     16
Investments                                  16
Current assets                               16
Current liabilities                          16
Book value of unquoted investments          109
Market value of quoted investments          109
Contingent liabilities                      109
Total Assets                                 16
Working capital                              16
Lease liabilities                            16
Inventory                                    16
Trade receivables                            16
Face value                                   26
Cash Equivalents                             16
Advance from Customers                      109
Trade Payables                               16
Number of equity shares preceding year      127
Debt preceding year                          54
Working capital preceding year               54
Net block preceding year                     54
Gross block preceding year                   83
Capital work in progress preceding year      54
Working capital 3Years back                 202
Working capital 5Years back                 581
Working capital 7Years back                 945
Working capital 10Years back               1336
Debt 3Years back                            202
Debt 5Years back                            581
Debt 7Years back                            945
Debt 10Years back                          1336
Net block 3Years back                       202
Net block 5Years back                       581
Net block 7Years back                       945
Market Capitalization                         0
join_key                                      0
dtype: int64
Name                                      0
BSE Code                                  0
NSE Code                                  0
Industry                                  0
Current Price                             1
Cash from operations last year           15
Free cash flow last year                 15
Cash from investing last year            15
Cash from financing last year            15
Net cash flow last year                  15
Cash beginning of last year              15
Cash end of last year                    36
Free cash flow preceding year            47
Cash from operations preceding year      47
Cash from investing preceding year       47
Cash from financing preceding year       47
Net cash flow preceding year             47
Cash beginning of preceding year         47
Cash end of preceding year               54
Free cash flow 3years                   133
Free cash flow 5years                   416
Free cash flow 7years                   861
Free cash flow 10years                 1333
Operating cash flow 3years              133
Operating cash flow 5years              416
Operating cash flow 7years              861
Operating cash flow 10years            1333
Investing cash flow 10years            1333
Investing cash flow 7years              861
Investing cash flow 5years              416
Investing cash flow 3years              133
Cash 3Years back                        202
Cash 5Years back                        581
Cash 7Years back                        945
Market Capitalization                     0
join_key                                  0
dtype: int64
Name                                            0
BSE Code                                        0
NSE Code                                        0
Industry                                        0
Current Price                                   1
Market Capitalization                           0
Price to Earning                             1041
Dividend yield                                 26
Price to book value                           494
Return on assets                               62
Debt to equity                                358
Return on equity                              435
Promoter holding                               15
Earnings yield                                 17
Pledged percentage                             15
Industry PE                                    22
Enterprise Value                               16
Number of equity shares                        20
Book value                                    128
Inventory turnover ratio                     1167
Quick ratio                                    21
Exports percentage                            379
Piotroski score                                 0
G Factor                                        0
Asset Turnover Ratio                           62
Financial leverage                             62
Number of Shareholders                         77
Unpledged promoter holding                     15
Return on invested capital                    122
Debtor days                                   333
Industry PBV                                    9
Credit rating                                4668
Working Capital Days                          333
Earning Power                                  19
Graham Number                                1224
Cash Conversion Cycle                         333
Days Payable Outstanding                     1667
Days Receivable Outstanding                   333
Days Inventory Outstanding                   1423
Public holding                                 77
FII holding                                    77
Change in FII holding                         225
Change in DII holding                         225
DII holding                                    77
Book value preceding year                     442
Return on capital employed preceding year     233
Return on assets preceding year               128
Return on equity preceding year               518
Number of Shareholders preceding quarter      225
join_key                                        0
dtype: int64
Name                                             0
BSE Code                                         0
NSE Code                                         0
Industry                                         0
Current Price                                    1
Number of equity shares 10years back          1276
Average return on equity 5Years               1101
Average return on equity 3Years                689
Book value 3years back                         824
Book value 5years back                         942
Book value 10years back                       1912
Inventory turnover ratio 3Years back          1368
Inventory turnover ratio 5Years back          1496
Inventory turnover ratio 7Years back          1722
Inventory turnover ratio 10Years back         2032
Exports percentage 3Years back                 407
Exports percentage 5Years back                 557
Average 5years dividend                        385
Average return on capital employed 3Years        0
Average return on capital employed 5Years        0
Average return on capital employed 7Years        0
Average return on capital employed 10Years       0
Average return on equity 10Years              1916
Average return on equity 7Years               1492
Return on equity 5years growth                1748
OPM 5Year                                      723
OPM 10Year                                    1621
Number of Shareholders 1year back              446
Average dividend payout 3years                 192
Average debtor days 3years                       0
Debtor days 3years back                        456
Debtor days 5years back                        781
Return on assets 5years                        603
Return on assets 3years                        219
Historical PE 3Years                           472
Historical PE 10Years                          182
Historical PE 7Years                           255
Historical PE 5Years                           339
Market Capitalization 3years back              739
Market Capitalization 5years back              929
Market Capitalization 7years back             1337
Market Capitalization 10years back            1855
Average Working Capital Days 3years              0
Change in FII holding 3Years                   706
Change in DII holding 3Years                   706
Market Capitalization                            0
join_key                                         0
dtype: int64
       Name  BSE Code  NSE Code  Industry  Current Price  Return over 3months  \
0     False     False     False     False          False                False
1     False     False     False     False          False                False
2     False     False     False     False          False                False
3     False     False     False     False          False                False
4     False     False     False     False          False                 True
...     ...       ...       ...       ...            ...                  ...
4663  False     False     False     False          False                False
4664  False     False     False     False          False                False
4665  False     False     False     False          False                False
4666  False     False     False     False          False                False
4667  False     False     False     False          False                False

      Return over 6months  Volume 1month average  Volume 1week average  \
0                   False                  False                 False
1                   False                  False                 False
2                   False                  False                 False
3                   False                  False                 False
4                    True                  False                 False
...                   ...                    ...                   ...
4663                False                  False                 False
4664                False                  False                 False
4665                False                  False                 False
4666                False                  False                 False
4667                False                  False                 False

      Volume  ...  MACD Signal  MACD Signal Previous Day  Return over 1year  \
0      False  ...        False                     False              False
1      False  ...        False                     False              False
2      False  ...        False                     False              False
3      False  ...        False                     False              False
4      False  ...        False                     False               True
...      ...  ...          ...                       ...                ...
4663   False  ...        False                     False              False
4664   False  ...        False                     False              False
4665   False  ...        False                     False              False
4666   False  ...        False                     False              False
4667   False  ...        False                     False              False

      Return over 3years  Return over 5years  Volume 1year average  \
0                  False               False                 False
1                  False               False                 False
2                  False                True                 False
3                  False               False                 False
4                   True                True                 False
...                  ...                 ...                   ...
4663               False               False                 False
4664               False               False                 False
4665               False               False                 False
4666               False               False                 False
4667               False               False                 False

      Return over 7years  Return over 10years  Market Capitalization  join_key
0                  False                False                  False     False
1                  False                False                  False     False
2                   True                 True                  False     False
3                  False                False                  False     False
4                   True                 True                  False     False
...                  ...                  ...                    ...       ...
4663               False                 True                  False     False
4664               False                False                  False     False
4665               False                False                  False     False
4666               False                False                  False     False
4667               False                False                  False     False

[4668 rows x 34 columns]

### CHECKING TOTAL NULL VALUES PRESENT IN ALL TABLES

In [56]:
tables = {
    "pl1": pl1,
    "pl2": pl2,
    "bs": bs,
    "cf": cf,
    "r1": r1,
    "r2": r2,
    "price": price
}

In [57]:
for name, df in tables.items():
    print(name)
    print(df.isnull().sum().sum())

pl1
4217
pl2
25159
bs
9675
cf
10420
r1
17124
r2
32429
price
6207

In [58]:
print(pl1.isnull())

       Name  BSE Code  NSE Code  Industry  Current Price  Sales    OPM  \
0     False     False     False     False          False  False  False
1     False     False     False     False          False  False  False
2     False     False     False     False          False  False  False
3     False     False     False     False          False  False  False
4     False     False     False     False          False  False  False
...     ...       ...       ...       ...            ...    ...    ...
4663  False     False     False     False          False  False  False
4664  False     False     False     False          False  False  False
4665  False     False     False     False          False  False  False
4666  False     False     False     False          False  False  False
4667  False     False     False     False          False  False  False

      Profit after tax  Return on capital employed    EPS  ...  \
0                False                       False  False  ...
1                False                       False  False  ...
2                False                       False  False  ...
3                False                       False  False  ...
4                False                       False  False  ...
...                ...                         ...    ...  ...
4663             False                       False  False  ...
4664             False                       False  False  ...
4665             False                       False  False  ...
4666             False                       False  False  ...
4667             False                       False  False  ...

      Extraordinary items preceding year  Net Profit preceding year  \
0                                  False                      False
1                                  False                      False
2                                  False                      False
3                                  False                      False
4                                  False                      False
...                                  ...                        ...
4663                               False                      False
4664                               False                      False
4665                               False                      False
4666                               False                      False
4667                               False                      False

      Dividend preceding year  OPM preceding year  NPM preceding year  \
0                       False               False               False
1                       False               False                True
2                       False               False               False
3                       False               False               False
4                       False               False               False
...                       ...                 ...                 ...
4663                    False               False               False
4664                    False               False               False
4665                    False               False               False
4666                    False               False               False
4667                    False               False               False

      EPS preceding year  Sales preceding 12months  \
0                  False                     False
1                  False                     False
2                  False                     False
3                  False                     False
4                  False                      True
...                  ...                       ...
4663               False                     False
4664               False                     False
4665               False                     False
4666               False                     False
4667               False                     False

      Net profit preceding 12months  Market Capitalization  join_key
0                             False                  False     False
1                             False                  False     False
2                             False                  False     False
3                             False                  False     False
4                              True                  False     False
...                             ...                    ...       ...
4663                          False                  False     False
4664                          False                  False     False
4665                          False                  False     False
4666                          False                  False     False
4667                          False                  False     False

[4668 rows x 58 columns]

In [59]:
r2.isnull().sum()

Name                                             0
BSE Code                                         0
NSE Code                                         0
Industry                                         0
Current Price                                    1
Number of equity shares 10years back          1276
Average return on equity 5Years               1101
Average return on equity 3Years                689
Book value 3years back                         824
Book value 5years back                         942
Book value 10years back                       1912
Inventory turnover ratio 3Years back          1368
Inventory turnover ratio 5Years back          1496
Inventory turnover ratio 7Years back          1722
Inventory turnover ratio 10Years back         2032
Exports percentage 3Years back                 407
Exports percentage 5Years back                 557
Average 5years dividend                        385
Average return on capital employed 3Years        0
Average return on capital employed 5Years        0
Average return on capital employed 7Years        0
Average return on capital employed 10Years       0
Average return on equity 10Years              1916
Average return on equity 7Years               1492
Return on equity 5years growth                1748
OPM 5Year                                      723
OPM 10Year                                    1621
Number of Shareholders 1year back              446
Average dividend payout 3years                 192
Average debtor days 3years                       0
Debtor days 3years back                        456
Debtor days 5years back                        781
Return on assets 5years                        603
Return on assets 3years                        219
Historical PE 3Years                           472
Historical PE 10Years                          182
Historical PE 7Years                           255
Historical PE 5Years                           339
Market Capitalization 3years back              739
Market Capitalization 5years back              929
Market Capitalization 7years back             1337
Market Capitalization 10years back            1855
Average Working Capital Days 3years              0
Change in FII holding 3Years                   706
Change in DII holding 3Years                   706
Market Capitalization                            0
join_key                                         0
dtype: int64

### FINDING COL WITH HIGHEST NULL %

In [60]:
(r2.isnull().sum() / len(r2)* 100).sort_values(ascending=False)

Inventory turnover ratio 10Years back         43.530420
Average return on equity 10Years              41.045416
Book value 10years back                       40.959726
Market Capitalization 10years back            39.738646
Return on equity 5years growth                37.446444
Inventory turnover ratio 7Years back          36.889460
OPM 10Year                                    34.725793
Inventory turnover ratio 5Years back          32.047986
Average return on equity 7Years               31.962296
Inventory turnover ratio 3Years back          29.305913
Market Capitalization 7years back             28.641817
Number of equity shares 10years back          27.335047
Average return on equity 5Years               23.586118
Book value 5years back                        20.179949
Market Capitalization 5years back             19.901457
Book value 3years back                        17.652099
Debtor days 5years back                       16.730934
Market Capitalization 3years back             15.831191
OPM 5Year                                     15.488432
Change in FII holding 3Years                  15.124250
Change in DII holding 3Years                  15.124250
Average return on equity 3Years               14.760069
Return on assets 5years                       12.917738
Exports percentage 5Years back                11.932305
Historical PE 3Years                          10.111397
Debtor days 3years back                        9.768638
Number of Shareholders 1year back              9.554413
Exports percentage 3Years back                 8.718937
Average 5years dividend                        8.247644
Historical PE 5Years                           7.262211
Historical PE 7Years                           5.462725
Return on assets 3years                        4.691517
Average dividend payout 3years                 4.113111
Historical PE 10Years                          3.898886
Current Price                                  0.021422
NSE Code                                       0.000000
BSE Code                                       0.000000
Name                                           0.000000
Industry                                       0.000000
Average debtor days 3years                     0.000000
Average return on capital employed 5Years      0.000000
Average return on capital employed 7Years      0.000000
Average return on capital employed 10Years     0.000000
Average return on capital employed 3Years      0.000000
Average Working Capital Days 3years            0.000000
Market Capitalization                          0.000000
join_key                                       0.000000
dtype: float64

In [61]:
(pl1.isnull().sum() / len(pl1)* 100).sort_values(ascending=False)

Sales preceding 12months              14.974293
Net profit preceding 12months         14.974293
OPM preceding year                     6.619537
OPM last year                          6.448158
OPM                                    6.448158
Material cost last year                6.448158
NPM preceding year                     5.141388
Return on capital employed             4.648672
NPM last year                          4.455870
EPS preceding year                     2.720651
Change in promoter holding             2.463582
Net Profit preceding year              0.921165
Operating profit preceding year        0.921165
Sales preceding year                   0.921165
EBIDT preceding year                   0.921165
Depreciation preceding year            0.921165
Interest preceding year                0.921165
EBIT preceding year                    0.921165
Other income preceding year            0.921165
Extraordinary items preceding year     0.921165
Dividend preceding year                0.921165
Profit before tax preceding year       0.921165
Tax preceding year                     0.921165
Profit after tax preceding year        0.921165
EPS                                    0.599829
EPS last year                          0.578406
Interest                               0.085690
Current Tax                            0.085690
Other income                           0.085690
Profit after tax                       0.085690
Sales                                  0.085690
Operating profit                       0.085690
EBIT                                   0.085690
Net profit                             0.085690
Depreciation                           0.085690
Tax                                    0.085690
Operating profit last year             0.064267
Sales last year                        0.064267
EBIDT last year                        0.064267
Profit after tax last year             0.064267
Profit before tax last year            0.064267
Interest last year                     0.064267
Other income last year                 0.064267
EBIT last year                         0.064267
Depreciation last year                 0.064267
Extraordinary items last year          0.064267
Tax last year                          0.064267
Employee cost last year                0.064267
Net Profit last year                   0.064267
Dividend last year                     0.064267
Last annual result date                0.064267
Current Price                          0.021422
NSE Code                               0.000000
Industry                               0.000000
BSE Code                               0.000000
Name                                   0.000000
Market Capitalization                  0.000000
join_key                               0.000000
dtype: float64

In [62]:
(pl2.isnull().sum() / len(pl2)* 100).sort_values(ascending=False)

EPS growth 10Years                   43.916024
Profit growth 10Years                43.530420
EBIDT growth 10Years                 40.124250
Sales growth 10Years                 37.103685
EPS growth 7Years                    34.640103
Profit growth 7Years                 34.640103
EBIDT growth 7Years                  30.655527
Sales growth 7Years                  28.663239
EPS growth 5Years                    26.585261
Average Earnings 10Year              26.435304
Average EBIT 10Year                  26.435304
Profit growth 5Years                 26.028278
EBIDT growth 5Years                  22.065124
Sales growth 5Years                  20.929734
EPS growth 3Years                    17.759212
Profit growth 3Years                 16.645244
Change in promoter holding 3Years    14.931448
EBIDT growth 3Years                  13.410454
Sales growth 3Years                  13.131962
Average Earnings 5Year                8.247644
Average EBIT 5Year                    8.247644
Sales growth 5years median            2.870608
Sales growth 10years median           1.949443
Current Price                         0.021422
Industry                              0.000000
NSE Code                              0.000000
BSE Code                              0.000000
Name                                  0.000000
Market Capitalization                 0.000000
join_key                              0.000000
dtype: float64

In [63]:
(r1.isnull().sum() / len(r1)* 100).sort_values(ascending=False)

Credit rating                                100.000000
Days Payable Outstanding                      35.711225
Days Inventory Outstanding                    30.484147
Graham Number                                 26.221080
Inventory turnover ratio                      25.000000
Price to Earning                              22.300771
Return on equity preceding year               11.096829
Price to book value                           10.582691
Book value preceding year                      9.468723
Return on equity                               9.318766
Exports percentage                             8.119109
Debt to equity                                 7.669237
Days Receivable Outstanding                    7.133676
Working Capital Days                           7.133676
Debtor days                                    7.133676
Cash Conversion Cycle                          7.133676
Return on capital employed preceding year      4.991431
Change in FII holding                          4.820051
Change in DII holding                          4.820051
Number of Shareholders preceding quarter       4.820051
Book value                                     2.742074
Return on assets preceding year                2.742074
Return on invested capital                     2.613539
Public holding                                 1.649529
FII holding                                    1.649529
Number of Shareholders                         1.649529
DII holding                                    1.649529
Return on assets                               1.328192
Asset Turnover Ratio                           1.328192
Financial leverage                             1.328192
Dividend yield                                 0.556984
Industry PE                                    0.471294
Quick ratio                                    0.449871
Number of equity shares                        0.428449
Earning Power                                  0.407027
Earnings yield                                 0.364182
Enterprise Value                               0.342759
Unpledged promoter holding                     0.321337
Pledged percentage                             0.321337
Promoter holding                               0.321337
Industry PBV                                   0.192802
Current Price                                  0.021422
NSE Code                                       0.000000
Market Capitalization                          0.000000
Industry                                       0.000000
BSE Code                                       0.000000
Name                                           0.000000
Piotroski score                                0.000000
G Factor                                       0.000000
join_key                                       0.000000
dtype: float64

In [64]:
(cf.isnull().sum() / len(cf)* 100).sort_values(ascending=False)

Operating cash flow 10years            28.556127
Free cash flow 10years                 28.556127
Investing cash flow 10years            28.556127
Cash 7Years back                       20.244216
Free cash flow 7years                  18.444730
Investing cash flow 7years             18.444730
Operating cash flow 7years             18.444730
Cash 5Years back                       12.446444
Operating cash flow 5years              8.911740
Investing cash flow 5years              8.911740
Free cash flow 5years                   8.911740
Cash 3Years back                        4.327335
Free cash flow 3years                   2.849186
Operating cash flow 3years              2.849186
Investing cash flow 3years              2.849186
Cash end of preceding year              1.156812
Cash from financing preceding year      1.006855
Cash from investing preceding year      1.006855
Free cash flow preceding year           1.006855
Cash from operations preceding year     1.006855
Cash beginning of preceding year        1.006855
Net cash flow preceding year            1.006855
Cash end of last year                   0.771208
Cash from operations last year          0.321337
Cash beginning of last year             0.321337
Net cash flow last year                 0.321337
Cash from investing last year           0.321337
Free cash flow last year                0.321337
Cash from financing last year           0.321337
Current Price                           0.021422
BSE Code                                0.000000
Name                                    0.000000
Industry                                0.000000
NSE Code                                0.000000
Market Capitalization                   0.000000
join_key                                0.000000
dtype: float64

In [65]:
(bs.isnull().sum() / len(bs)* 100).sort_values(ascending=False)

Debt 10Years back                          28.620394
Working capital 10Years back               28.620394
Working capital 7Years back                20.244216
Debt 7Years back                           20.244216
Net block 7Years back                      20.244216
Net block 5Years back                      12.446444
Debt 5Years back                           12.446444
Working capital 5Years back                12.446444
Working capital 3Years back                 4.327335
Debt 3Years back                            4.327335
Net block 3Years back                       4.327335
Number of equity shares preceding year      2.720651
Accumulated depreciation                    2.335047
Gross block                                 2.335047
Advance from Customers                      2.335047
Revaluation reserve                         2.335047
Preference capital                          2.335047
Unsecured loan                              2.335047
Secured loan                                2.335047
Contingent liabilities                      2.335047
Book value of unquoted investments          2.335047
Market value of quoted investments          2.335047
Gross block preceding year                  1.778063
Capital work in progress preceding year     1.156812
Net block preceding year                    1.156812
Debt preceding year                         1.156812
Working capital preceding year              1.156812
Equity capital                              0.771208
Face value                                  0.556984
Capital work in progress                    0.342759
Net block                                   0.342759
Debt                                        0.342759
Reserves                                    0.342759
Current assets                              0.342759
Investments                                 0.342759
Trade Payables                              0.342759
Cash Equivalents                            0.342759
Trade receivables                           0.342759
Current liabilities                         0.342759
Total Assets                                0.342759
Balance sheet total                         0.342759
Lease liabilities                           0.342759
Inventory                                   0.342759
Working capital                             0.342759
Current Price                               0.021422
BSE Code                                    0.000000
NSE Code                                    0.000000
Industry                                    0.000000
Name                                        0.000000
Market Capitalization                       0.000000
join_key                                    0.000000
dtype: float64

In [66]:
(price.isnull().sum() / len(price)* 100).sort_values(ascending=False)

Return over 10years         40.659811
Return over 7years          31.041131
Return over 5years          23.843188
Return over 3years          18.080548
Return over 1year            8.804627
Return over 6months          4.391602
Return over 3months          2.249357
Return over 1month           1.006855
RSI                          0.728363
Return over 1week            0.364182
MACD Signal Previous Day     0.192802
MACD Previous Day            0.192802
DMA 50 previous day          0.192802
DMA 200 previous day         0.192802
Return over 1day             0.149957
High price all time          0.107112
Low price all time           0.107112
High price                   0.107112
MACD Signal                  0.107112
Low price                    0.107112
DMA 200                      0.107112
MACD                         0.107112
DMA 50                       0.107112
Current Price                0.021422
BSE Code                     0.000000
Name                         0.000000
NSE Code                     0.000000
Volume 1month average        0.000000
Volume 1week average         0.000000
Industry                     0.000000
Volume                       0.000000
Volume 1year average         0.000000
Market Capitalization        0.000000
join_key                     0.000000
dtype: float64

### CREATING COPIES OF TABLES

In [67]:
pl1_clean=pl1.copy()
pl2_clean=pl2.copy()
r1_clean=r1.copy()
r2_clean=r2.copy()
bs_clean=bs.copy()
cf_clean=cf.copy()
price_clean=price.copy()

### HANDALING NULL VALUES

In [ ]:
r1_clean.drop(columns=['Credit rating'], inplace=True)
# bec credit rating column has 99% missing values, so it is better to drop it from the dataset.

In [70]:
for name, df in {
    "pl1": pl1_clean,
    "pl2": pl2_clean,
    "r1": r1_clean,
    "r2": r2_clean,
    "bs": bs_clean,
    "cf": cf_clean,
    "price": price_clean
}.items():
    print("\n",name)
    print((df.isnull().mean()*100).sort_values(ascending=False).head(5))


    # it is better to drop the columns with more than 50% missing values, and for the columns with less than 50% missing values, we can impute the missing values with mean or median.

 pl1
Sales preceding 12months         14.974293
Net profit preceding 12months    14.974293
OPM preceding year                6.619537
OPM last year                     6.448158
OPM                               6.448158
dtype: float64

 pl2
EPS growth 10Years       43.916024
Profit growth 10Years    43.530420
EBIDT growth 10Years     40.124250
Sales growth 10Years     37.103685
EPS growth 7Years        34.640103
dtype: float64

 r1
Credit rating                 100.000000
Days Payable Outstanding       35.711225
Days Inventory Outstanding     30.484147
Graham Number                  26.221080
Inventory turnover ratio       25.000000
dtype: float64

 r2
Inventory turnover ratio 10Years back    43.530420
Average return on equity 10Years         41.045416
Book value 10years back                  40.959726
Market Capitalization 10years back       39.738646
Return on equity 5years growth           37.446444
dtype: float64

 bs
Debt 10Years back               28.620394
Working capital 10Years back    28.620394
Working capital 7Years back     20.244216
Debt 7Years back                20.244216
Net block 7Years back           20.244216
dtype: float64

 cf
Operating cash flow 10years    28.556127
Free cash flow 10years         28.556127
Investing cash flow 10years    28.556127
Cash 7Years back               20.244216
Free cash flow 7years          18.444730
dtype: float64

 price
Return over 10years    40.659811
Return over 7years     31.041131
Return over 5years     23.843188
Return over 3years     18.080548
Return over 1year       8.804627
dtype: float64

In [72]:
r1_clean.columns.tolist()

['Name',
 'BSE Code',
 'NSE Code',
 'Industry',
 'Current Price',
 'Market Capitalization',
 'Price to Earning',
 'Dividend yield',
 'Price to book value',
 'Return on assets',
 'Debt to equity',
 'Return on equity',
 'Promoter holding',
 'Earnings yield',
 'Pledged percentage',
 'Industry PE',
 'Enterprise Value',
 'Number of equity shares',
 'Book value',
 'Inventory turnover ratio',
 'Quick ratio',
 'Exports percentage',
 'Piotroski score',
 'G Factor',
 'Asset Turnover Ratio',
 'Financial leverage',
 'Number of Shareholders',
 'Unpledged promoter holding',
 'Return on invested capital',
 'Debtor days',
 'Industry PBV',
 'Credit rating',
 'Working Capital Days',
 'Earning Power',
 'Graham Number',
 'Cash Conversion Cycle',
 'Days Payable Outstanding',
 'Days Receivable Outstanding',
 'Days Inventory Outstanding',
 'Public holding',
 'FII holding',
 'Change in FII holding',
 'Change in DII holding',
 'DII holding',
 'Book value preceding year',
 'Return on capital employed preceding year',
 'Return on assets preceding year',
 'Return on equity preceding year',
 'Number of Shareholders preceding quarter',
 'join_key']

### FINDING MISSING VALUES

In [ ]:
for df in [pl1_clean, pl2_clean, r1_clean, r2_clean, bs_clean, cf_clean, price_clean]:
    num_cols = df.select_dtypes(include='number').columns
    df[num_cols] = df[num_cols].fillna(df[num_cols].median())

# fill the missing values in the numerical columns with median values because median is more robust to outliers than mean.

In [78]:
for name, df in {
    "pl1": pl1_clean,
    "pl2": pl2_clean,
    "r1": r1_clean,
    "r2": r2_clean,
    "bs": bs_clean,
    "cf": cf_clean,
    "price": price_clean
}.items():
    print(name,df.isnull().sum().sum())

pl1 0
pl2 0
r1 4668
r2 0
bs 0
cf 0
price 0

In [80]:
r1_clean.isnull().sum()

Name                                            0
BSE Code                                        0
NSE Code                                        0
Industry                                        0
Current Price                                   0
Market Capitalization                           0
Price to Earning                                0
Dividend yield                                  0
Price to book value                             0
Return on assets                                0
Debt to equity                                  0
Return on equity                                0
Promoter holding                                0
Earnings yield                                  0
Pledged percentage                              0
Industry PE                                     0
Enterprise Value                                0
Number of equity shares                         0
Book value                                      0
Inventory turnover ratio                        0
Quick ratio                                     0
Exports percentage                              0
Piotroski score                                 0
G Factor                                        0
Asset Turnover Ratio                            0
Financial leverage                              0
Number of Shareholders                          0
Unpledged promoter holding                      0
Return on invested capital                      0
Debtor days                                     0
Industry PBV                                    0
Credit rating                                4668
Working Capital Days                            0
Earning Power                                   0
Graham Number                                   0
Cash Conversion Cycle                           0
Days Payable Outstanding                        0
Days Receivable Outstanding                     0
Days Inventory Outstanding                      0
Public holding                                  0
FII holding                                     0
Change in FII holding                           0
Change in DII holding                           0
DII holding                                     0
Book value preceding year                       0
Return on capital employed preceding year       0
Return on assets preceding year                 0
Return on equity preceding year                 0
Number of Shareholders preceding quarter        0
join_key                                        0
dtype: int64

In [81]:
r1_clean.drop(columns=['Credit rating'], inplace=True)

In [82]:
r1_clean.isnull().sum()

Name                                         0
BSE Code                                     0
NSE Code                                     0
Industry                                     0
Current Price                                0
Market Capitalization                        0
Price to Earning                             0
Dividend yield                               0
Price to book value                          0
Return on assets                             0
Debt to equity                               0
Return on equity                             0
Promoter holding                             0
Earnings yield                               0
Pledged percentage                           0
Industry PE                                  0
Enterprise Value                             0
Number of equity shares                      0
Book value                                   0
Inventory turnover ratio                     0
Quick ratio                                  0
Exports percentage                           0
Piotroski score                              0
G Factor                                     0
Asset Turnover Ratio                         0
Financial leverage                           0
Number of Shareholders                       0
Unpledged promoter holding                   0
Return on invested capital                   0
Debtor days                                  0
Industry PBV                                 0
Working Capital Days                         0
Earning Power                                0
Graham Number                                0
Cash Conversion Cycle                        0
Days Payable Outstanding                     0
Days Receivable Outstanding                  0
Days Inventory Outstanding                   0
Public holding                               0
FII holding                                  0
Change in FII holding                        0
Change in DII holding                        0
DII holding                                  0
Book value preceding year                    0
Return on capital employed preceding year    0
Return on assets preceding year              0
Return on equity preceding year              0
Number of Shareholders preceding quarter     0
join_key                                     0
dtype: int64

In [83]:
for name, df in {
    "pl1": pl1_clean,
    "pl2": pl2_clean,
    "r1": r1_clean,
    "r2": r2_clean,
    "bs": bs_clean,
    "cf": cf_clean,
    "price": price_clean
}.items():
    print(name,df.isnull().sum().sum())

pl1 0
pl2 0
r1 0
r2 0
bs 0
cf 0
price 0

### IMPORTING CLEANED FILES

In [88]:
pl1_clean.to_csv("PL1_Clean.csv", index=False)
pl2_clean.to_csv("PL2_Clean.csv", index=False)
bs_clean.to_csv("BS_Clean.csv", index=False)
cf_clean.to_csv("CF_Clean.csv", index=False)
r1_clean.to_csv("R1_Clean.csv", index=False)
r2_clean.to_csv("R2_Clean.csv", index=False)
price_clean.to_csv("Price_Clean.csv", index=False)